version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./...
    ldflags:
      - -s -w -X x46/confy/internal/buildinfo.Version={{.Version}} -X x46/confy/internal/buildinfo.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
      - "386"

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
      

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
